In [6]:
import pandas as pd
import numpy as np

import seaborn as sns
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [7]:
import pandas as pd

# Assuming your file is in Excel format, use read_excel
data = pd.read_csv('/content/drive/MyDrive/new_bangladesh_student/new_Anxiety.csv')
data.head()

,Age,Gender,University,Department,Academic Year,Current CGPA,Anxiety Level
0,18-22,Female,"Independent University, Bangladesh (IUB)",Engineering - CS / CSE / CSC / Similar to CS,Fourth Year or Equivalent,2.50 - 2.99,Moderate Anxiety
1,18-22,Male,"Independent University, Bangladesh (IUB)",Engineering - CS / CSE / CSC / Similar to CS,First Year or Equivalent,3.80 - 4.00,Mild Anxiety
2,18-22,Male,"Independent University, Bangladesh (IUB)",Engineering - CS / CSE / CSC / Similar to CS,First Year or Equivalent,3.00 - 3.39,Moderate Anxiety
3,18-22,Male,"Independent University, Bangladesh (IUB)",Engineering - CS / CSE / CSC / Similar to CS,First Year or Equivalent,3.40 - 3.79,Mild Anxiety
4,18-22,Male,"Independent University, Bangladesh (IUB)",Engineering - CS / CSE / CSC / Similar to CS,First Year or Equivalent,3.40 - 3.79,Mild Anxiety

In [3]:
# Check null values in each column
null_values = data.isnull().sum()

print("Null values in each column:")
print(null_values)

# Display only columns with missing values
print("\nColumns containing missing values:")
print(null_values[null_values > 0])

# Total number of missing values in the dataset
print("\nTotal missing values in the dataset:", data.isnull().sum().sum())

Null values in each column:
Age              0
Gender           0
University       0
Department       0
Academic Year    0
Current CGPA     0
Anxiety Level    0
dtype: int64

Columns containing missing values:
Series([], dtype: int64)

Total missing values in the dataset: 0

In [4]:
# Identify categorical columns
categorical_cols = data.select_dtypes(include=['object', 'category']).columns

print("Categorical columns:")
print(categorical_cols.tolist())

# Show number of unique categories for each categorical column
print("\nNumber of unique categories:")
for col in categorical_cols:
    print(f"{col}: {data[col].nunique()} categories")

Categorical columns:
['Age', 'Gender', 'University', 'Department', 'Academic Year', 'Current CGPA', 'Anxiety Level']

Number of unique categories:
Age: 5 categories
Gender: 3 categories
University: 15 categories
Department: 12 categories
Academic Year: 5 categories
Current CGPA: 6 categories
Anxiety Level: 4 categories

In [5]:
# Check all columns and their categories
for col in data.columns:
    print(f"\nColumn: {col}")
    print(f"Data Type: {data[col].dtype}")
    print(f"Number of Unique Categories: {data[col].nunique()}")
    print("Categories/Values:")
    print(data[col].unique())
    print("-" * 50)

Column: Age
Data Type: object
Number of Unique Categories: 5
Categories/Values:
['18-22' '23-26' 'Below 18' '27-30' 'Above 30']
--------------------------------------------------

Column: Gender
Data Type: object
Number of Unique Categories: 3
Categories/Values:
['Female' 'Male' 'Prefer not to say']
--------------------------------------------------

Column: University
Data Type: object
Number of Unique Categories: 15
Categories/Values:
['Independent University, Bangladesh (IUB)' 'Daffodil University'
 'Bangladesh University of Engineering and Technology (BUET)'
 'BRAC University' 'Dhaka University (DU)' 'North South University (NSU)'
 'American International University Bangladesh (AIUB)'
 'Dhaka University of Engineering and Technology (DUET)'
 'Rajshahi University (RU)' 'Islamic University of Technology (IUT)'
 'United International University (UIU)'
 'Patuakhali Science and Technology University'
 'Rajshahi University of Engineering and Technology (RUET)'
 'East West University (EWU)' 'Bangladesh Agricultural University (BAU)']
--------------------------------------------------

Column: Department
Data Type: object
Number of Unique Categories: 12
Categories/Values:
['Engineering - CS / CSE / CSC / Similar to CS' 'Other'
 'Engineering - EEE/ ECE / Similar to EEE'
 'Environmental and Life Sciences' 'Business and Entrepreneurship Studies'
 'Pharmacy and Public Health' 'Biological Sciences'
 'Engineering - Civil Engineering / Similar to CE'
 'Engineering - Mechanical Engineering / Similar to ME'
 'Engineering - Other' 'Law and Human Rights'
 'Liberal Arts and Social Sciences']
--------------------------------------------------

Column: Academic Year
Data Type: object
Number of Unique Categories: 5
Categories/Values:
['Fourth Year or Equivalent' 'First Year or Equivalent'
 'Third Year or Equivalent' 'Second Year or Equivalent' 'Other']
--------------------------------------------------

Column: Current CGPA
Data Type: object
Number of Unique Categories: 6
Categories/Values:
['2.50 - 2.99' '3.80 - 4.00' '3.00 - 3.39' '3.40 - 3.79' 'Below 2.50'
 'Other']
--------------------------------------------------

Column: Anxiety Level
Data Type: object
Number of Unique Categories: 4
Categories/Values:
['Moderate Anxiety' 'Mild Anxiety' 'Minimal Anxiety' 'Severe Anxiety']
--------------------------------------------------

In [9]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Load dataset
data = pd.read_csv('/content/drive/MyDrive/new_bangladesh_student/new_Anxiety.csv')

# Columns for One-Hot Encoding
onehot_cols = [
    'Age',
    'Gender',
    'Academic Year',
    'Current CGPA'
]

# Columns for Label Encoding
label_cols = [
    'University',
    'Department'
]

# One-Hot Encoding (0/1 format)
data = pd.get_dummies(data, columns=onehot_cols, dtype=int)

# Label Encoding for University and Department
label_encoder = LabelEncoder()

for col in label_cols:
    data[col] = label_encoder.fit_transform(data[col])

# Custom encoding for Anxiety Level
anxiety_mapping = {
    'Minimal Anxiety': 0,
    'Mild Anxiety': 1,
    'Moderate Anxiety': 2,
    'Severe Anxiety': 3
}

data['Anxiety Level'] = data['Anxiety Level'].map(anxiety_mapping)

# Save processed dataset
save_path = '/content/drive/MyDrive/new_bangladesh_student/new_Anxiety1.csv'
data.to_csv(save_path, index=False)

print("Encoding completed successfully!")
print("Saved at:", save_path)

# Check encoded Anxiety Level distribution
print(data['Anxiety Level'].value_counts().sort_index())

data.head()

Encoding completed successfully!
Saved at: /content/drive/MyDrive/new_bangladesh_student/new_Anxiety1.csv
Anxiety Level
0    158
1    495
2    610
3    714
Name: count, dtype: int64

,University,Department,Anxiety Level,Age_18-22,Age_23-26,Age_27-30,Age_Above 30,Age_Below 18,Gender_Female,Gender_Male,...,Academic Year_Fourth Year or Equivalent,Academic Year_Other,Academic Year_Second Year or Equivalent,Academic Year_Third Year or Equivalent,Current CGPA_2.50 - 2.99,Current CGPA_3.00 - 3.39,Current CGPA_3.40 - 3.79,Current CGPA_3.80 - 4.00,Current CGPA_Below 2.50,Current CGPA_Other
0,8,2,2,1,0,0,0,0,1,0,...,1,0,0,0,1,0,0,0,0,0
1,8,2,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
2,8,2,2,1,0,0,0,0,0,1,...,0,0,0,0,0,1,0,0,0,0
3,8,2,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
4,8,2,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0