In [2]:
import pandas as pd
import numpy as np

import seaborn as sns
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [1]:
import pandas as pd

# Assuming your file is in Excel format, use read_excel
data = pd.read_csv('/content/drive/MyDrive/new_bangladesh_student/new_Stress4.csv')
data.head()

,University,Department,Stress Level,Age_18-22,Age_23-26,Age_27-30,Gender_Female,Gender_Male,Academic Year_Second Year,Current CGPA_2.50 - 2.99,Current CGPA_3.40 - 3.79
0,8,2,1,1,0,0,1,0,0,1,0
1,8,2,1,1,0,0,0,1,0,0,0
2,8,2,1,1,0,0,0,1,0,0,0
3,8,2,1,1,0,0,0,1,0,0,1
4,8,2,1,1,0,0,0,1,0,0,1

In [2]:
data

,University,Department,Stress Level,Age_18-22,Age_23-26,Age_27-30,Gender_Female,Gender_Male,Academic Year_Second Year,Current CGPA_2.50 - 2.99,Current CGPA_3.40 - 3.79
0,8,2,1,1,0,0,1,0,0,1,0
1,8,2,1,1,0,0,0,1,0,0,0
2,8,2,1,1,0,0,0,1,0,0,0
3,8,2,1,1,0,0,0,1,0,0,1
4,8,2,1,1,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...
1972,2,0,1,0,1,0,0,1,0,0,1
1973,2,10,1,0,1,0,1,0,0,0,1
1974,2,0,2,0,1,0,1,0,0,0,0
1975,2,10,1,0,1,0,0,1,0,0,0
1976,8,2,1,0,1,0,0,1,0,1,0

In [3]:
import pandas as pd

# Drop the 'Abundance' column from the DataFrame to create the feature matrix X
X = data.drop('Stress Level', axis=1)

# Extract the 'Abundance' column as the target variable y
y = data['Stress Level']

# Print the feature matrix X and target variable y
print(X)
print(y)

      University  Department  Age_18-22  Age_23-26  Age_27-30  Gender_Female  \
0              8           2          1          0          0              1
1              8           2          1          0          0              0
2              8           2          1          0          0              0
3              8           2          1          0          0              0
4              8           2          1          0          0              0
...          ...         ...        ...        ...        ...            ...
1972           2           0          0          1          0              0
1973           2          10          0          1          0              1
1974           2           0          0          1          0              1
1975           2          10          0          1          0              0
1976           8           2          0          1          0              0

      Gender_Male  Academic Year_Second Year  Current CGPA_2.50 - 2.99  \
0               0                          0                         1
1               1                          0                         0
2               1                          0                         0
3               1                          0                         0
4               1                          0                         0
...           ...                        ...                       ...
1972            1                          0                         0
1973            0                          0                         0
1974            0                          0                         0
1975            1                          0                         0
1976            1                          0                         1

      Current CGPA_3.40 - 3.79
0                            0
1                            0
2                            0
3                            1
4                            1
...                        ...
1972                         1
1973                         1
1974                         0
1975                         0
1976                         0

[1977 rows x 10 columns]
0       1
1       1
2       1
3       1
4       1
       ..
1972    1
1973    1
1974    2
1975    1
1976    1
Name: Stress Level, Length: 1977, dtype: int64

In [4]:
from sklearn.model_selection import train_test_split
# Split the data into train, test, and validation sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=42)

In [5]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix, precision_recall_curve, auc
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, roc_curve, auc
from sklearn.metrics import precision_score, recall_score, f1_score, precision_recall_curve, f1_score


# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=42)



# Initialize the logistic regression classifier
logistic_classifier = LogisticRegression(max_iter=1000, C=2.0)

# Define the custom equation coefficients
beta_a0 = -2.0  # Intercept
beta_a1 = 0.5   # Coefficient for the feature X

# Train the model
logistic_classifier.fit(X_train, y_train)

# Model testing and evaluation
y_pred = logistic_classifier.predict(X_test)

# Calculate accuracy, precision, recall, and F1-score
accuracy = accuracy_score(y_test, y_pred)
precision_weighted = precision_score(y_test, y_pred, average='weighted')
precision_micro = precision_score(y_test, y_pred, average='micro')
precision_macro = precision_score(y_test, y_pred, average='macro')
precision_per_class = precision_score(y_test, y_pred, average=None)

# Generate and plot classification report
class_report = classification_report(y_test, y_pred)

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [9]:
!pip uninstall -y shapash scikit-learn
!pip install scikit-learn==1.3.2
!pip install shapash==2.7.8

Found existing installation: shapash 2.7.8
Uninstalling shapash-2.7.8:
  Successfully uninstalled shapash-2.7.8
Found existing installation: scikit-learn 1.5.2
Uninstalling scikit-learn-1.5.2:
  Successfully uninstalled scikit-learn-1.5.2
Collecting scikit-learn==1.3.2
  Using cached scikit_learn-1.3.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Requirement already satisfied: numpy<2.0,>=1.17.3 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.3.2) (1.26.4)
Requirement already satisfied: scipy>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.3.2) (1.16.3)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.3.2) (1.5.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.3.2) (3.6.0)
Using cached scikit_learn-1.3.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (10.8 MB)
Installing collected packages: scikit-learn
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
spopt 0.7.0 requires scikit-learn>=1.4.0, but you have scikit-learn 1.3.2 which is incompatible.
esda 2.9.0 requires scikit-learn>=1.4, but you have scikit-learn 1.3.2 which is incompatible.
hdbscan 0.8.44 requires scikit-learn>=1.6, but you have scikit-learn 1.3.2 which is incompatible.
mapclassify 2.10.0 requires scikit-learn>=1.4, but you have scikit-learn 1.3.2 which is incompatible.
libpysal 4.14.1 requires scikit-learn>=1.4.0, but you have scikit-learn 1.3.2 which is incompatible.
umap-learn 0.5.12 requires scikit-learn>=1.6, but you have scikit-learn 1.3.2 which is incompatible.
imbalanced-learn 0.14.2 requires scikit-learn<2,>=1.4.2, but you have scikit-learn 1.3.2 which is incompatible.
Successfully installed scikit-learn-1.3.2

Collecting shapash==2.7.8
  Using cached shapash-2.7.8-py3-none-any.whl.metadata (25 kB)
Requirement already satisfied: plotly<6.0.0,>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from shapash==2.7.8) (5.24.1)
Requirement already satisfied: matplotlib>=3.2.0 in /usr/local/lib/python3.12/dist-packages (from shapash==2.7.8) (3.10.0)
Requirement already satisfied: numpy<2,>1.18.0 in /usr/local/lib/python3.12/dist-packages (from shapash==2.7.8) (1.26.4)
Requirement already satisfied: pandas>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from shapash==2.7.8) (2.2.2)
Requirement already satisfied: shap>=0.45.0 in /usr/local/lib/python3.12/dist-packages (from shapash==2.7.8) (0.49.1)
Requirement already satisfied: Flask>=1.0.4 in /usr/local/lib/python3.12/dist-packages (from shapash==2.7.8) (3.1.3)
Requirement already satisfied: dash>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from shapash==2.7.8) (4.4.1)
Requirement already satisfied: dash-bootstrap-components>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from shapash==2.7.8) (2.0.4)
Requirement already satisfied: dash-core-components>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from shapash==2.7.8) (2.0.0)
Requirement already satisfied: dash-daq>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from shapash==2.7.8) (0.6.0)
Requirement already satisfied: dash-html-components>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from shapash==2.7.8) (2.0.0)
Requirement already satisfied: dash-renderer==1.8.3 in /usr/local/lib/python3.12/dist-packages (from shapash==2.7.8) (1.8.3)
Requirement already satisfied: dash-table>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from shapash==2.7.8) (5.0.0)
Requirement already satisfied: nbformat>4.2.0 in /usr/local/lib/python3.12/dist-packages (from shapash==2.7.8) (5.10.4)
Requirement already satisfied: numba>=0.53.1 in /usr/local/lib/python3.12/dist-packages (from shapash==2.7.8) (0.60.0)
Collecting scikit-learn<1.6.0,>=1.4.0 (from shapash==2.7.8)
  Using cached scikit_learn-1.5.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
Requirement already satisfied: category_encoders>=2.6.0 in /usr/local/lib/python3.12/dist-packages (from shapash==2.7.8) (2.7.0)
Requirement already satisfied: scipy>=0.19.1 in /usr/local/lib/python3.12/dist-packages (from shapash==2.7.8) (1.16.3)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from category_encoders>=2.6.0->shapash==2.7.8) (1.0.2)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders>=2.6.0->shapash==2.7.8) (0.14.6)
Requirement already satisfied: Werkzeug<3.2 in /usr/local/lib/python3.12/dist-packages (from dash>=2.3.1->shapash==2.7.8) (3.1.8)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.12/dist-packages (from dash>=2.3.1->shapash==2.7.8) (9.0.0)
Requirement already satisfied: typing_extensions>=4.1.1 in /usr/local/lib/python3.12/dist-packages (from dash>=2.3.1->shapash==2.7.8) (4.16.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from dash>=2.3.1->shapash==2.7.8) (2.32.4)
Requirement already satisfied: retrying in /usr/local/lib/python3.12/dist-packages (from dash>=2.3.1->shapash==2.7.8) (1.4.2)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.12/dist-packages (from dash>=2.3.1->shapash==2.7.8) (1.6.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from dash>=2.3.1->shapash==2.7.8) (75.2.0)
Requirement already satisfied: janus>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from dash>=2.3.1->shapash==2.7.8) (2.0.0)
Requirement already satisfied: pydantic>=2.10 in /usr/local/lib/python3.12/dist-packages (from dash>=2.3.1->shapash==2.7.8) (2.13.4)
Requirement already satisfied: comm in /usr/local/lib/python3.12/dist-packages (from dash>=2.3.1->shapash==2.7.8) (0.2.3)
Requirement already satisfied: blinker>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from Flask>=1.0.4->shapash==2.7.8) (1.9.0)
Requirement already satisfied: click>=8.1.3 in /usr/local/lib/python3.12/dist-packages (from Flask>=1.0.4->shapash==2.7.8) (8.4.2)
Requirement already satisfied: itsdangerous>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from Flask>=1.0.4->shapash==2.7.8) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in /usr/local/lib/python3.12/dist-packages (from Flask>=1.0.4->shapash==2.7.8) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from Flask>=1.0.4->shapash==2.7.8) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.2.0->shapash==2.7.8) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.2.0->shapash==2.7.8) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.2.0->shapash==2.7.8) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.2.0->shapash==2.7.8) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.2.0->shapash==2.7.8) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.2.0->shapash==2.7.8) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.2.0->shapash==2.7.8) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.2.0->shapash==2.7.8) (2.9.0.post0)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat>4.2.0->shapash==2.7.8) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.12/dist-packages (from nbformat>4.2.0->shapash==2.7.8) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbformat>4.2.0->shapash==2.7.8) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in /usr/local/lib/python3.12/dist-packages (from nbformat>4.2.0->shapash==2.7.8) (5.7.1)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba>=0.53.1->shapash==2.7.8) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.1.0->shapash==2.7.8) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.1.0->shapash==2.7.8) (2026.3)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly<6.0.0,>=5.0.0->shapash==2.7.8) (9.1.4)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<1.6.0,>=1.4.0->shapash==2.7.8) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<1.6.0,>=1.4.0->shapash==2.7.8) (3.6.0)
Requirement already satisfied: tqdm>=4.27.0 in /usr/local/lib/python3.12/dist-packages (from shap>=0.45.0->shapash==2.7.8) (4.67.3)
Requirement already satisfied: slicer==0.0.8 in /usr/local/lib/python3.12/dist-packages (from shap>=0.45.0->shapash==2.7.8) (0.0.8)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.12/dist-packages (from shap>=0.45.0->shapash==2.7.8) (3.1.2)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat>4.2.0->shapash==2.7.8) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat>4.2.0->shapash==2.7.8) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat>4.2.0->shapash==2.7.8) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat>4.2.0->shapash==2.7.8) (2026.6.3)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core!=5.0.*,>=4.12->nbformat>4.2.0->shapash==2.7.8) (4.10.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.10->dash>=2.3.1->shapash==2.7.8) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.10->dash>=2.3.1->shapash==2.7.8) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.10->dash>=2.3.1->shapash==2.7.8) (0.4.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.2.0->shapash==2.7.8) (1.17.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib-metadata->dash>=2.3.1->shapash==2.7.8) (4.1.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->dash>=2.3.1->shapash==2.7.8) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->dash>=2.3.1->shapash==2.7.8) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->dash>=2.3.1->shapash==2.7.8) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->dash>=2.3.1->shapash==2.7.8) (2026.6.17)
Using cached shapash-2.7.8-py3-none-any.whl (19.1 MB)
Using cached scikit_learn-1.5.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.9 MB)
Installing collected packages: scikit-learn, shapash
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.3.2
    Uninstalling scikit-learn-1.3.2:
      Successfully uninstalled scikit-learn-1.3.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
hdbscan 0.8.44 requires scikit-learn>=1.6, but you have scikit-learn 1.5.2 which is incompatible.
umap-learn 0.5.12 requires scikit-learn>=1.6, but you have scikit-learn 1.5.2 which is incompatible.
Successfully installed scikit-learn-1.5.2 shapash-2.7.8

In [6]:
from shapash import SmartExplainer

# Initialize SHAPASH explainer with the logistic regression classifier
xpl = SmartExplainer(model=logistic_classifier)

# Predict on test data
y_pred = logistic_classifier.predict(X_test)

# Convert y_pred to a pandas Series with the same index as X_test
y_pred_series = pd.Series(y_pred, index=X_test.index)

# Compile the explainer with test data and predicted values
xpl.compile(x=X_test, y_pred=y_pred_series)

# Plot feature importance
xpl.plot.features_importance()

INFO: Shap explainer type - <shap.explainers._exact.ExactExplainer object at 0x7ee79c50e6f0>

ExactExplainer explainer: 397it [00:16, 14.55it/s]

In [7]:
print("Indices in your dataset:", X_test.index)

Indices in your dataset: Index([1827, 1889,  678,  351, 1105,  610,   70, 1125,   56, 1952,
       ...
       1681,  570,  966, 1686, 1588,   71,  764,  259,   51,  198],
      dtype='int64', length=396)

In [8]:
from shapash.explainer.smart_explainer import SmartExplainer

# Initialize SHAPASH explainer with the logistic regression classifier
xpl = SmartExplainer(model=logistic_classifier)

# Predict on test data
y_pred = logistic_classifier.predict(X_test)

# Convert y_pred to a pandas Series with the same index as X_test
y_pred_series = pd.Series(y_pred, index=X_test.index)

# Compile the explainer with test data and predicted values
xpl.compile(x=X_test, y_pred=y_pred_series)

# Generate the comparison plot for a specific index (1827 in this case)
index_to_visualize = 1827
xpl.plot.compare_plot(index=[index_to_visualize])

INFO: Shap explainer type - <shap.explainers._exact.ExactExplainer object at 0x7ee7994b3f20>

ExactExplainer explainer: 397it [00:10,  1.98it/s]
/usr/local/lib/python3.12/dist-packages/shapash/plots/plot_line_comparison.py:65: UserWarning:

Comparison needs at least 2 individuals

In [9]:
from shapash.explainer.smart_explainer import SmartExplainer

# Initialize SHAPASH explainer with the logistic regression classifier
xpl = SmartExplainer(model=logistic_classifier)

# Predict on test data
y_pred = logistic_classifier.predict(X_test)

# Convert y_pred to a pandas Series with the same index as X_test
y_pred_series = pd.Series(y_pred, index=X_test.index)

# Compile the explainer with test data and predicted values
xpl.compile(x=X_test, y_pred=y_pred_series)

# Generate the comparison plot for specific indices
indices_to_visualize = [1827, 1889, 678, 351, 1105]
xpl.plot.compare_plot(index=indices_to_visualize)

INFO: Shap explainer type - <shap.explainers._exact.ExactExplainer object at 0x7ee799396a50>

ExactExplainer explainer: 397it [00:10,  2.66it/s]

In [10]:
# Generate individual SHAP contribution plot for a specific index
index_to_visualize = 1827
xpl.plot.local_plot(index=index_to_visualize)